#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/piggymetrics?createDatabaseIfNotExist=true
#    username: root
#    password: 
#    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    database: mysql
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#    properties:
#      hibernate:
#        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
#        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  context-path: /uaa
  port: 5000