server:
  port: 9411
spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411/zipkin/
    flush-interval: 10
  sleuth:
    sampler:
      percentage: 1.0
zipkin:
  storage:
    type: mysql
    strict-trace-id: true